@hostname = localhost
@port = 5001
@host = {{hostname}}:{{port}}

### Get all movies
GET http://{{host}}/api/movies HTTP/1.1
Content-Type: application/json

### Get movie by ID
GET http://{{host}}/api/movies/REPLACE_WITH_MOVIE_UUID HTTP/1.1
Content-Type: application/json

### Create movie
POST http://{{host}}/api/movies HTTP/1.1
Content-Type: application/json

{
  "title": "Inception",
  "overview": "A thief steals secrets through dream-sharing technology.",
  "releaseYear": 2010,
  "genre": ["Sci-Fi", "Thriller"],
  "runtime": 148,
  "posterUrl": "https://example.com/inception.jpg",
  "createdBy": "REPLACE_WITH_USER_UUID"
}


### Update movie
PUT http://{{host}}/api/movies/REPLACE_WITH_MOVIE_UUID HTTP/1.1
Content-Type: application/json

{
  "title": "Inception (Updated)",
  "runtime": 150
}


### Delete movie
DELETE http://{{host}}/api/movies/REPLACE_WITH_MOVIE_UUID HTTP/1.1
Content-Type: application/json

###

POST http://{{host}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "fast-winker",
    "email": "faster@example.com",
    "password": "fast-winker"
}

###
POST http://{{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "faster@example.com",
    "password": "fast-winker"
}

###
POST http://{{host}}/api/auth/logout HTTP/1.1

###
POST http://{{host}}/api/watchlist HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkNzJkMjllLWMxOGUtNDViZC04ODNjLTJjY2Y5ZjRkNDUwOCIsImlhdCI6MTc3MzAwMjEwNiwiZXhwIjoxNzczNjA2OTA2fQ.sF8MUkuC8XjwXrBvUUc9WCRtSNpOd84GAdtRPv7AaKA

{
    "movieId": "98e42cf9-6d84-4fc6-a55b-3316c3dca7f7",
    "status": "PLANNED",
    "rating": 5,
    "notes": "This is a must watch for hackers"
}
